language: python
python:
  - 2.7
  - 3.4
  - 3.5
sudo: false

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy nose mkl future
  - pip install nose-cov python-coveralls
  - python setup.py install

# Run test
script:
  - nosetests --with-cov --cov pyMKL --cov-config .coveragerc -v -s

# Calculate coverage
after_success:
  - coveralls

notifications:
  email:
    - dwfmarchant@gmail.com
    - brendan@bitsmithy.net
